### ISSUE TITLE
Create a System Overview for user docs

### ISSUE THREAD

**Issue by jbogarthyde** [in-toto/docs#88]
Copy sections of the in-toto Technical Specification into source for a system overview page.
-  [ ] Create a System Overview page in the [doc source](https://github.com/in-toto/docs) directory. 
-  [ ] Copy and adapt the content of [System Overview](https://github.com/in-toto/docs/blob/v1.0/in-toto-spec.md#2-system-overview) as the first part of the content.
-  [ ] Copy and adapt the content [Final Product](https://github.com/in-toto/docs/blob/v1.0/in-toto-spec.md#3-the-final-product) as the next part of the content.
    - [ ]  At the end of this page, link to [Document Formats](https://github.com/in-toto/docs/blob/v1.0/in-toto-spec.md#4-document-formats) for further detailed information.
    - [ ]  Add links to new System Overview document. Add as first item on the Docs Home Page, and second menu item of the "Documentation" menu on the [main website](https://in-toto.io/).
  
See [Umbrella Issue](https://github.com/in-toto/docs/issues/85#top)

**Comment by jbogarthyde** [comment]
Please add the documentation label to this issue
